name: Web CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: web-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: '1'
      NEXT_PUBLIC_FIREBASE_API_KEY: 'demo'
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'demo.firebaseapp.com'
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'demo-project'
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'demo-project.appspot.com'
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '000000000000'
      NEXT_PUBLIC_FIREBASE_APP_ID: '1:000000000000:web:demo'
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ''
      NEXT_PUBLIC_ENABLE_REACT_GRAB: 'false'
      FIREBASE_STORAGE_BUCKET: 'demo-project.appspot.com'
      GOOGLE_CLOUD_PROJECT: 'demo-project'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint (web)
        run: npm run lint:web

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests
        run: npm test

      - name: Build
        run: npm run build
